### ISSUE TITLE
Compiling OpenCL >= 2.0  for RX 580 (polaris)

### ISSUE THREAD

**Issue by sabbaghm** [ROCm/clang-ocl#11]
I wanted to compile an OpenCL program targeting RX 580 GPU using the clang-ocl and/or rocm flow, but in the build log it says:

Error: Failed to compile OpenCL source (from CL to LLVM IR).

I am using `atomic` types and methods in my kernel (e.g. `atomic_int` and `atomic_load_explicit()'), however, it considers them **unknown** or **undeclared identifier**.

What is the procedure to compile an OpenCL >= 2.0 program using ROCm flow?

Thank you!

**Comment by ppanchad-amd** [comment]
@sabbaghm Apologies for the lack of response. RX580 is not officially supported in our latest ROCm 6.1.2. Thanks!
